---------------------------
-- Tipos de ACTIVOS
---------------------------
Insert into ACTIVOS.TIPOS_ACTIVOS (ID,NOMBRE) values ('12','Edificio');
Insert into ACTIVOS.TIPOS_ACTIVOS (ID,NOMBRE) values ('13','Computadora');
---------------------------
-- Tipos Transacciones
---------------------------
Insert into ACTIVOS.TIPOS_TRANSACCIONES (ID,NOMBRE) values ('7','Compra');
Insert into ACTIVOS.TIPOS_TRANSACCIONES (ID,NOMBRE) values ('8','Donación');
---------------------------
-- Estados ACTIVOS
---------------------------
Insert into ACTIVOS.ESTADOS_ACTIVOS (ID,NOMBRE) values ('0','Prestado');
Insert into ACTIVOS.ESTADOS_ACTIVOS (ID,NOMBRE) values ('3','Asignado');
Insert into ACTIVOS.ESTADOS_ACTIVOS (ID,NOMBRE) values ('4','Disponible');
Insert into ACTIVOS.ESTADOS_ACTIVOS (ID,NOMBRE) values ('5','Dañado sin reparación');
Insert into ACTIVOS.ESTADOS_ACTIVOS (ID,NOMBRE) values ('6','Perdido o robado');

-------------------------
-- Datos Activos
-------------------------
Insert into ACTIVOS.ACTIVOS (ID,NUMERO_SERIE,FECHA_COMPRA,INICIO_SERVICIO,FECHA_INGRESO,FABRICANTE,PRECIO,DESCRIPCION,EXENTO,PRESTABLE,TIPO_CAPITAL,INGRESADO_POR,NUMERO_DOCUMENTO,NUMERO_LOTE,TIPO_TRANSACCIONID,ESTADO_ACTIVOID,TIPO_ACTIVOID,ANFITRIONAID,PROVEEDORIDPROVEEDOR,COMENTARIO,DESECHADO,USUARIOSIDUSUARIO,ESTACIONID,DEPARTAMENTOIDDEPARTAMENTO,MODELO) values ('5','88720929109',to_date('02/02/14','DD/MM/RR'),null,to_date('22/08/14','DD/MM/RR'),'Apple','1000','Pequeña descripción','1','1','0','Fabian','882929','90','7','0','13','02','ANURA0120062005.0102708472',null,'0',null,null,null,'MacBook Pro');
Insert into ACTIVOS.ACTIVOS (ID,NUMERO_SERIE,FECHA_COMPRA,INICIO_SERVICIO,FECHA_INGRESO,FABRICANTE,PRECIO,DESCRIPCION,EXENTO,PRESTABLE,TIPO_CAPITAL,INGRESADO_POR,NUMERO_DOCUMENTO,NUMERO_LOTE,TIPO_TRANSACCIONID,ESTADO_ACTIVOID,TIPO_ACTIVOID,ANFITRIONAID,PROVEEDORIDPROVEEDOR,COMENTARIO,DESECHADO,USUARIOSIDUSUARIO,ESTACIONID,DEPARTAMENTOIDDEPARTAMENTO,MODELO) values ('6','98u9oas908u9',to_date('09/09/08','DD/MM/RR'),null,to_date('09/09/08','DD/MM/RR'),'Huawei','1999','Otra pequeña descripción','1','0','0','Fabian','89u9','9','7','0','13','01','CYCLO010104112013093451031',null,'0',null,null,null,'Nexus 6p');
Insert into ACTIVOS.ACTIVOS (ID,NUMERO_SERIE,FECHA_COMPRA,INICIO_SERVICIO,FECHA_INGRESO,FABRICANTE,PRECIO,DESCRIPCION,EXENTO,PRESTABLE,TIPO_CAPITAL,INGRESADO_POR,NUMERO_DOCUMENTO,NUMERO_LOTE,TIPO_TRANSACCIONID,ESTADO_ACTIVOID,TIPO_ACTIVOID,ANFITRIONAID,PROVEEDORIDPROVEEDOR,COMENTARIO,DESECHADO,USUARIOSIDUSUARIO,ESTACIONID,DEPARTAMENTOIDDEPARTAMENTO,MODELO) values ('7','8879',to_date('08/09/01','DD/MM/RR'),null,to_date('01/09/04','DD/MM/RR'),'OnePlus','450','Otra pequeñísima descripción','0','1','0','Pedro','77881919','1','7','0','12','01','ANURA0120062005.0101243749',null,'0',null,null,null,'One');
Insert into ACTIVOS.ACTIVOS (ID,NUMERO_SERIE,FECHA_COMPRA,INICIO_SERVICIO,FECHA_INGRESO,FABRICANTE,PRECIO,DESCRIPCION,EXENTO,PRESTABLE,TIPO_CAPITAL,INGRESADO_POR,NUMERO_DOCUMENTO,NUMERO_LOTE,TIPO_TRANSACCIONID,ESTADO_ACTIVOID,TIPO_ACTIVOID,ANFITRIONAID,PROVEEDORIDPROVEEDOR,COMENTARIO,DESECHADO,USUARIOSIDUSUARIO,ESTACIONID,DEPARTAMENTOIDDEPARTAMENTO,MODELO) values ('8','0909910',to_date('01/01/02','DD/MM/RR'),null,to_date('07/04/05','DD/MM/RR'),'OnePlus','600','Otra pequeñísima descripción','1','0','0','Carlos','98y98yu9','9','8','0','13','02','CYCLO010104112013093451031',null,'0',null,null,null,'Two');
