
CREATE SEQUENCE
INSERT_NUMERO_BOLETA
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE
/

CREATE OR REPLACE TRIGGER num_boleta
BEFORE INSERT ON PRESTAMOS
FOR EACH ROW
BEGIN
SELECT INSERT_NUMERO_BOLETA.nextval
INTO :new.NUMERO_BOLETA from dual;
END;