//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos_PrestamosOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO_SOLICITADO
    {
        public string ID_PRESTAMO { get; set; }
        public string TIPO_ACTIVO { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> CANTIDADAPROBADA { get; set; }
    
        public virtual PRESTAMO PRESTAMO { get; set; }
    }
}
