//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos_PrestamosOET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrestamosEntities : DbContext
    {
        public PrestamosEntities()
            : base("name=PrestamosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EQUIPO_SOLICITADO> EQUIPO_SOLICITADO { get; set; }
        public virtual DbSet<PRESTAMO> PRESTAMOS { get; set; }
        public virtual DbSet<ACTIVO> ACTIVOS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<TIPOS_ACTIVOS> TIPOS_ACTIVOS { get; set; }
    }
}
