-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 23/04/2016 10:12:29 p.m.
-- Generated from EDMX file: C:\Users\andre_000\Documents\GitHub\ProyectoActivosPrestamos\Activos-PrestamosOET\Models\PrestamosOET.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------
-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- DROP TABLE "ACTIVOS"."ACTIVOPRESTAMO";

-- DROP TABLE "ACTIVOS"."ACTIVOS";

-- DROP TABLE "ACTIVOS"."EQUIPO_SOLICITADO";

-- DROP TABLE "ACTIVOS"."PRESTAMOS";

-- DROP TABLE "ACTIVOS"."TIPOS_ACTIVOS";

-- DROP TABLE "ACTIVOS"."USUARIOS";

-- DROP TABLE "V_ANFITRIONA";

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'EQUIPO_SOLICITADO'
CREATE TABLE "ACTIVOS"."EQUIPO_SOLICITADO" (
   "ID_PRESTAMO" VARCHAR2(8 CHAR) NOT NULL,
   "TIPO_ACTIVO" VARCHAR2(50 CHAR) NOT NULL,
   "CANTIDAD" NUMBER(38) NOT NULL
);

-- Creating table 'PRESTAMOS'
CREATE TABLE "ACTIVOS"."PRESTAMOS" (
   "ID" VARCHAR2(8 CHAR) NOT NULL,
   "NUMERO_BOLETA" NUMBER(19) ,
   "MOTIVO" VARCHAR2(250 CHAR) ,
   "FECHA_SOLICITUD" DATE NOT NULL,
   "FECHA_RETIRO" DATE NOT NULL,
   "PERIODO_USO" NUMBER(38) NOT NULL,
   "SOFTWARE_REQUERIDO" VARCHAR2(250 CHAR) ,
   "OBSERVACIONES_SOLICITANTE" VARCHAR2(250 CHAR) ,
   "OBSERVACIONES_APROBADO" VARCHAR2(250 CHAR) ,
   "OBSERVACIONES_RECIBIDO" VARCHAR2(250 CHAR) ,
   "SIGLA_CURSO" CHAR(8 CHAR) ,
   "Estado" NUMBER(5) NOT NULL,
   "CED_SOLICITA" VARCHAR2(26 CHAR) NOT NULL,
   "CED_APRUEBA" VARCHAR2(26 CHAR) 
);

-- Creating table 'ACTIVOS'
CREATE TABLE "ACTIVOS"."ACTIVOS" (
   "ID" NUMBER(10) NOT NULL,
   "NUMERO_SERIE" NVARCHAR2(64) ,
   "FECHA_COMPRA" DATE NOT NULL,
   "INICIO_SERVICIO" DATE ,
   "FECHA_INGRESO" DATE NOT NULL,
   "FABRICANTE" NVARCHAR2(64) NOT NULL,
   "PRECIO" NUMBER(10) NOT NULL,
   "DESCRIPCION" NVARCHAR2(256) NOT NULL,
   "EXENTO" NUMBER(1) NOT NULL,
   "PRESTABLE" NUMBER(1) NOT NULL,
   "TIPO_CAPITAL" NUMBER(1) NOT NULL,
   "INGRESADO_POR" NVARCHAR2(128) NOT NULL,
   "NUMERO_DOCUMENTO" NVARCHAR2(32) NOT NULL,
   "NUMERO_LOTE" NVARCHAR2(32) ,
   "TIPO_TRANSACCIONID" NUMBER(10) NOT NULL,
   "ESTADO_ACTIVOID" NUMBER(10) NOT NULL,
   "TIPO_ACTIVOID" NUMBER(10) NOT NULL,
   "ANFITRIONAID" VARCHAR2(2 CHAR) NOT NULL,
   "PROVEEDORIDPROVEEDOR" VARCHAR2(50 CHAR) NOT NULL,
   "COMENTARIO" NVARCHAR2(256) ,
   "DESECHADO" NUMBER(1) NOT NULL,
   "USUARIOSIDUSUARIO" VARCHAR2(26 CHAR) ,
   "ESTACIONID" VARCHAR2(26 CHAR) ,
   "DEPARTAMENTOIDDEPARTAMENTO" NUMBER(8,2) ,
   "MODELO" NVARCHAR2(128) 
);

-- Creating table 'USUARIOS'
CREATE TABLE "ACTIVOS"."USUARIOS" (
   "USUARIO1" VARCHAR2(50 CHAR) NOT NULL,
   "CLAVE" VARCHAR2(50 CHAR) ,
   "ANFITRION" VARCHAR2(2 CHAR) NOT NULL,
   "IDCONTACTO" VARCHAR2(26 CHAR) NOT NULL,
   "IDUSUARIO" VARCHAR2(26 CHAR) NOT NULL,
   "DESCRIPCION" VARCHAR2(255 CHAR) ,
   "NOMBRE" VARCHAR2(100 CHAR) NOT NULL,
   "IDESTACION" VARCHAR2(26 CHAR) NOT NULL,
   "ESTADO" NUMBER(38) NOT NULL,
   "CORREO" VARCHAR2(400 CHAR) 
);

-- Creating table 'TIPOS_ACTIVOS'
CREATE TABLE "ACTIVOS"."TIPOS_ACTIVOS" (
   "ID" NUMBER(10) NOT NULL,
   "NOMBRE" NVARCHAR2(127) NOT NULL
);

-- Creating table 'V_ANFITRIONA'
CREATE TABLE "ACTIVOS"."V_ANFITRIONA" (
   "ID" VARCHAR2(2 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(100 CHAR) NOT NULL,
   "SIGLAS" VARCHAR2(20 CHAR) NOT NULL,
   "MONEDA" VARCHAR2(26 CHAR) NOT NULL,
   "TIPOCAMBIO" VARCHAR2(10 CHAR) NOT NULL,
   "TIPOUSUARIO" NUMBER(38) NOT NULL,
   "TIPOCAMBIO_CONTA" VARCHAR2(10 CHAR) NOT NULL,
   "MONEDA_CONTA" VARCHAR2(26 CHAR) NOT NULL
);

-- Creating table 'V_ESTACION'
CREATE TABLE "ACTIVOS"."V_ESTACION" (
   "ID" VARCHAR2(26 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(100 CHAR) NOT NULL,
   "SIGLAS" VARCHAR2(20 CHAR) ,
   "RESERVABLE" VARCHAR2(1 CHAR) 
);

-- Creating table 'V_MONEDA'
CREATE TABLE "ACTIVOS"."V_MONEDA" (
   "ID" VARCHAR2(26 CHAR) NOT NULL,
   "NOMBRE" VARCHAR2(50 CHAR) ,
   "SIMBOLO" VARCHAR2(3 CHAR) 
);

-- Creating table 'V_PROVEEDOR'
CREATE TABLE "ACTIVOS"."V_PROVEEDOR" (
   "IDPROVEEDOR" VARCHAR2(50 CHAR) NOT NULL,
   "FECHAINGRESO" DATE NOT NULL,
   "NOMBRE" VARCHAR2(50 CHAR) NOT NULL,
   "RAZONSOCIAL" VARCHAR2(50 CHAR) ,
   "ESTADO" NUMBER(1) NOT NULL,
   "TIPOCEDULA" NUMBER(10) ,
   "CEDULA" VARCHAR2(50 CHAR) NOT NULL,
   "TELEFONO" VARCHAR2(50 CHAR) ,
   "FAX" VARCHAR2(50 CHAR) ,
   "SITIOWEB" VARCHAR2(100 CHAR) ,
   "CORREOELECTRONICO" VARCHAR2(50 CHAR) ,
   "LOCACION" NUMBER(1) NOT NULL,
   "IDPAIS" VARCHAR2(50 CHAR) ,
   "IDPROVINCIA" VARCHAR2(50 CHAR) ,
   "DIRECCION" VARCHAR2(255 CHAR) ,
   "IDFORMAPAGO" VARCHAR2(50 CHAR) ,
   "IDPLAZO" VARCHAR2(50 CHAR) ,
   "DESCUENTO" NUMBER(8,2) ,
   "INTERESMORA" NUMBER(8,2) ,
   "COMENTARIO" VARCHAR2(255 CHAR) ,
   "CONGELAR" NUMBER(1) ,
   "CREADO" DATE NOT NULL,
   "CREADOR" VARCHAR2(50 CHAR) NOT NULL,
   "MODIFICADO" DATE NOT NULL,
   "MODIFICADOR" VARCHAR2(50 CHAR) NOT NULL,
   "MONEDA" VARCHAR2(26 CHAR) ,
   "NOMBRE_CORTO" VARCHAR2(20 CHAR) 
);

-- Creating table 'ACTIVOPRESTAMO'
CREATE TABLE "ACTIVOS"."ACTIVOPRESTAMO" (
   "ACTIVOes_ID" NUMBER(10) NOT NULL,
   "PRESTAMOes_ID" VARCHAR2(8 CHAR) NOT NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID_PRESTAMO", "TIPO_ACTIVO", "CANTIDAD"in table 'EQUIPO_SOLICITADO'
ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO"
ADD CONSTRAINT "PK_EQUIPO_SOLICITADO"
   PRIMARY KEY ("ID_PRESTAMO", "TIPO_ACTIVO", "CANTIDAD" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PRESTAMOS'
ALTER TABLE "ACTIVOS"."PRESTAMOS"
ADD CONSTRAINT "PK_PRESTAMOS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "PK_ACTIVOS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "IDUSUARIO"in table 'USUARIOS'
ALTER TABLE "ACTIVOS"."USUARIOS"
ADD CONSTRAINT "PK_USUARIOS"
   PRIMARY KEY ("IDUSUARIO" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TIPOS_ACTIVOS'
ALTER TABLE "ACTIVOS"."TIPOS_ACTIVOS"
ADD CONSTRAINT "PK_TIPOS_ACTIVOS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID", "NOMBRE", "SIGLAS", "MONEDA", "TIPOCAMBIO", "TIPOUSUARIO", "TIPOCAMBIO_CONTA", "MONEDA_CONTA"in table 'V_ANFITRIONA'
ALTER TABLE "ACTIVOS"."V_ANFITRIONA"
ADD CONSTRAINT "PK_V_ANFITRIONA"
   PRIMARY KEY ("ID", "NOMBRE", "SIGLAS", "MONEDA", "TIPOCAMBIO", "TIPOUSUARIO", "TIPOCAMBIO_CONTA", "MONEDA_CONTA" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID", "NOMBRE"in table 'V_ESTACION'
ALTER TABLE "ACTIVOS"."V_ESTACION"
ADD CONSTRAINT "PK_V_ESTACION"
   PRIMARY KEY ("ID", "NOMBRE" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'V_MONEDA'
ALTER TABLE "ACTIVOS"."V_MONEDA"
ADD CONSTRAINT "PK_V_MONEDA"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "IDPROVEEDOR", "FECHAINGRESO", "NOMBRE", "ESTADO", "CEDULA", "LOCACION", "CREADO", "CREADOR", "MODIFICADO", "MODIFICADOR"in table 'V_PROVEEDOR'
ALTER TABLE "ACTIVOS"."V_PROVEEDOR"
ADD CONSTRAINT "PK_V_PROVEEDOR"
   PRIMARY KEY ("IDPROVEEDOR", "FECHAINGRESO", "NOMBRE", "ESTADO", "CEDULA", "LOCACION", "CREADO", "CREADOR", "MODIFICADO", "MODIFICADOR" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ACTIVOes_ID", "PRESTAMOes_ID"in table 'ACTIVOPRESTAMO'
ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO"
ADD CONSTRAINT "PK_ACTIVOPRESTAMO"
   PRIMARY KEY ("ACTIVOes_ID", "PRESTAMOes_ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "ID_PRESTAMO" in table 'EQUIPO_SOLICITADO'
ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO"
ADD CONSTRAINT "FK_A_PRESTAMOS"
   FOREIGN KEY ("ID_PRESTAMO")
   REFERENCES "ACTIVOS"."PRESTAMOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_A_PRESTAMOS'
CREATE INDEX "IX_FK_A_PRESTAMOS"
ON "ACTIVOS"."EQUIPO_SOLICITADO"
   ("ID_PRESTAMO");

-- Creating foreign key on "ACTIVOes_ID" in table 'ACTIVOPRESTAMO'
ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO"
ADD CONSTRAINT "FK_ACTIVOPRESTAMO_ACTIVO"
   FOREIGN KEY ("ACTIVOes_ID")
   REFERENCES "ACTIVOS"."ACTIVOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_ACTIVOPRESTAMO_ACTIVO'
CREATE INDEX "IX_FK_ACTIVOPRESTAMO_ACTIVO"
ON "ACTIVOS"."ACTIVOPRESTAMO"
   ("ACTIVOes_ID");

-- Creating foreign key on "PRESTAMOes_ID" in table 'ACTIVOPRESTAMO'
ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO"
ADD CONSTRAINT "FK_ACTIVOPRESTAMO_PRESTAMO"
   FOREIGN KEY ("PRESTAMOes_ID")
   REFERENCES "ACTIVOS"."PRESTAMOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_ACTIVOPRESTAMO_PRESTAMO'
CREATE INDEX "IX_FK_ACTIVOPRESTAMO_PRESTAMO"
ON "ACTIVOS"."ACTIVOPRESTAMO"
   ("PRESTAMOes_ID");

-- Creating foreign key on "CED_SOLICITA" in table 'PRESTAMOS'
ALTER TABLE "ACTIVOS"."PRESTAMOS"
ADD CONSTRAINT "FK_Solicita"
   FOREIGN KEY ("CED_SOLICITA")
   REFERENCES "ACTIVOS"."USUARIOS"
       ("IDUSUARIO")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_Solicita'
CREATE INDEX "IX_FK_Solicita"
ON "ACTIVOS"."PRESTAMOS"
   ("CED_SOLICITA");

-- Creating foreign key on "CED_APRUEBA" in table 'PRESTAMOS'
ALTER TABLE "ACTIVOS"."PRESTAMOS"
ADD CONSTRAINT "FK_Aprueba"
   FOREIGN KEY ("CED_APRUEBA")
   REFERENCES "ACTIVOS"."USUARIOS"
       ("IDUSUARIO")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_Aprueba'
CREATE INDEX "IX_FK_Aprueba"
ON "ACTIVOS"."PRESTAMOS"
   ("CED_APRUEBA");

-- Creating foreign key on "TIPO_ACTIVOID" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_TIPO_ACTIVOACTIVO"
   FOREIGN KEY ("TIPO_ACTIVOID")
   REFERENCES "ACTIVOS"."TIPOS_ACTIVOS"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_TIPO_ACTIVOACTIVO'
CREATE INDEX "IX_FK_TIPO_ACTIVOACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("TIPO_ACTIVOID");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
