-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 18/05/2016 09:59:33
-- Generated from EDMX file: C:\Users\Carolina\Documents\GitHub\ProyectoActivosPrestamos\Activos-PrestamosOET\Models\PrestamosOET.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

-- ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO" DROP CONSTRAINT "FK_A_PRESTAMOS" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO" DROP CONSTRAINT "FK_ACTIVOPRESTAMO_ACTIVO" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO" DROP CONSTRAINT "FK_ACTIVOPRESTAMO_PRESTAMO" CASCADE;

-- ALTER TABLE "ACTIVOS"."PRESTAMOS" DROP CONSTRAINT "FK_Aprueba" CASCADE;

-- ALTER TABLE "ACTIVOS"."PRESTAMOS" DROP CONSTRAINT "FK_Solicita" CASCADE;

-- ALTER TABLE "ACTIVOS"."ACTIVOS" DROP CONSTRAINT "FK_TIPO_ACTIVOACTIVO" CASCADE;
-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- DROP TABLE "ACTIVOS"."ACTIVOPRESTAMO";

-- DROP TABLE "ACTIVOS"."ACTIVOS";

-- DROP TABLE "ACTIVOS"."EQUIPO_SOLICITADO";

-- DROP TABLE "ACTIVOS"."PRESTAMOS";

-- DROP TABLE "ACTIVOS"."TIPOS_ACTIVOS";

-- DROP TABLE "ACTIVOS"."USUARIOS";

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'EQUIPO_SOLICITADO'
CREATE TABLE "ACTIVOS"."EQUIPO_SOLICITADO" (
   "ID_PRESTAMO" VARCHAR2(25 ) NOT NULL,
   "TIPO_ACTIVO" VARCHAR2(50 ) NOT NULL,
   "CANTIDAD" NUMBER(38) NOT NULL,
   "CANTIDADAPROBADA" NUMBER(38) ,
   "TIPOS_ACTIVOSID" NUMBER(10) NOT NULL
);

-- Creating table 'PRESTAMOS'
CREATE TABLE "ACTIVOS"."PRESTAMOS" (
   "ID" VARCHAR2(25 ) NOT NULL,
   "NUMERO_BOLETA" NUMBER(19) ,
   "MOTIVO" VARCHAR2(250 ) ,
   "FECHA_SOLICITUD" DATE NOT NULL,
   "FECHA_RETIRO" DATE NOT NULL,
   "PERIODO_USO" NUMBER(10) NOT NULL,
   "SOFTWARE_REQUERIDO" VARCHAR2(250 ) ,
   "OBSERVACIONES_SOLICITANTE" VARCHAR2(250 ) ,
   "OBSERVACIONES_APROBADO" VARCHAR2(250 ) ,
   "OBSERVACIONES_RECIBIDO" VARCHAR2(250 ) ,
   "SIGLA_CURSO" CHAR(8 ) ,
   "Estado" NUMBER(5) NOT NULL,
   "CED_SOLICITA" VARCHAR2(26 ) NOT NULL,
   "CED_APRUEBA" VARCHAR2(26 ) 
);

-- Creating table 'ACTIVOS'
CREATE TABLE "ACTIVOS"."ACTIVOS" (
   "ID" NCLOB NOT NULL,
   "NUMERO_SERIE" NVARCHAR2(64) ,
   "FECHA_COMPRA" DATE NOT NULL,
   "INICIO_SERVICIO" DATE ,
   "FECHA_INGRESO" DATE NOT NULL,
   "FABRICANTE" NVARCHAR2(64) NOT NULL,
   "PRECIO" NUMBER(10) NOT NULL,
   "DESCRIPCION" NVARCHAR2(256) NOT NULL,
   "EXENTO" NUMBER(1) NOT NULL,
   "PRESTABLE" NUMBER(1) NOT NULL,
   "TIPO_CAPITAL" NUMBER(1) NOT NULL,
   "INGRESADO_POR" NVARCHAR2(128) NOT NULL,
   "NUMERO_DOCUMENTO" NVARCHAR2(32) NOT NULL,
   "NUMERO_LOTE" NVARCHAR2(32) ,
   "TIPO_TRANSACCIONID" NUMBER(10) NOT NULL,
   "ESTADO_ACTIVOID" NUMBER(10) NOT NULL,
   "TIPO_ACTIVOID" NUMBER(10) NOT NULL,
   "ANFITRIONAID" VARCHAR2(2 ) NOT NULL,
   "PROVEEDORIDPROVEEDOR" VARCHAR2(50 ) NOT NULL,
   "COMENTARIO" NVARCHAR2(256) ,
   "DESECHADO" NUMBER(1) NOT NULL,
   "USUARIOSIDUSUARIO" VARCHAR2(26 ) ,
   "ESTACIONID" VARCHAR2(26 ) ,
   "DEPARTAMENTOIDDEPARTAMENTO" NUMBER(8,2) ,
   "MODELO" NVARCHAR2(128) 
);

-- Creating table 'USUARIOS'
CREATE TABLE "ACTIVOS"."USUARIOS" (
   "USUARIO1" VARCHAR2(50 ) NOT NULL,
   "CLAVE" VARCHAR2(50 ) ,
   "ANFITRION" VARCHAR2(2 ) NOT NULL,
   "IDCONTACTO" VARCHAR2(26 ) NOT NULL,
   "IDUSUARIO" VARCHAR2(26 ) NOT NULL,
   "DESCRIPCION" VARCHAR2(255 ) ,
   "NOMBRE" VARCHAR2(100 ) NOT NULL,
   "IDESTACION" VARCHAR2(26 ) NOT NULL,
   "ESTADO" NUMBER(38) NOT NULL,
   "CORREO" VARCHAR2(400 ) 
);

-- Creating table 'TIPOS_ACTIVOS'
CREATE TABLE "ACTIVOS"."TIPOS_ACTIVOS" (
   "ID" NUMBER(10) NOT NULL,
   "NOMBRE" NVARCHAR2(127) NOT NULL
);

-- Creating table 'ACTIVOPRESTAMO'
CREATE TABLE "ACTIVOS"."ACTIVOPRESTAMO" (
   "ACTIVOes_ID" NCLOB NOT NULL,
   "PRESTAMOes_ID" VARCHAR2(25 ) NOT NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID_PRESTAMO", "TIPO_ACTIVO", "CANTIDAD"in table 'EQUIPO_SOLICITADO'
ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO"
ADD CONSTRAINT "PK_EQUIPO_SOLICITADO"
   PRIMARY KEY ("ID_PRESTAMO", "TIPO_ACTIVO", "CANTIDAD" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PRESTAMOS'
ALTER TABLE "ACTIVOS"."PRESTAMOS"
ADD CONSTRAINT "PK_PRESTAMOS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "PK_ACTIVOS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "IDUSUARIO"in table 'USUARIOS'
ALTER TABLE "ACTIVOS"."USUARIOS"
ADD CONSTRAINT "PK_USUARIOS"
   PRIMARY KEY ("IDUSUARIO" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TIPOS_ACTIVOS'
ALTER TABLE "ACTIVOS"."TIPOS_ACTIVOS"
ADD CONSTRAINT "PK_TIPOS_ACTIVOS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ACTIVOes_ID", "PRESTAMOes_ID"in table 'ACTIVOPRESTAMO'
ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO"
ADD CONSTRAINT "PK_ACTIVOPRESTAMO"
   PRIMARY KEY ("ACTIVOes_ID", "PRESTAMOes_ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "ID_PRESTAMO" in table 'EQUIPO_SOLICITADO'
ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO"
ADD CONSTRAINT "FK_A_PRESTAMOS"
   FOREIGN KEY ("ID_PRESTAMO")
   REFERENCES "ACTIVOS"."PRESTAMOS"
       ("ID")
   
  ;

-- Creating index for FOREIGN KEY 'FK_A_PRESTAMOS'
CREATE INDEX "IX_FK_A_PRESTAMOS"
ON "ACTIVOS"."EQUIPO_SOLICITADO"
   ("ID_PRESTAMO");

-- Creating foreign key on "ACTIVOes_ID" in table 'ACTIVOPRESTAMO'
ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO"
ADD CONSTRAINT "FK_ACTIVOPRESTAMO_ACTIVO"
   FOREIGN KEY ("ACTIVOes_ID")
   REFERENCES "ACTIVOS"."ACTIVOS"
       ("ID")
;

-- Creating index for FOREIGN KEY 'FK_ACTIVOPRESTAMO_ACTIVO'
CREATE INDEX "IX_FK_ACTIVOPRESTAMO_ACTIVO"
ON "ACTIVOS"."ACTIVOPRESTAMO"
   ("ACTIVOes_ID");

-- Creating foreign key on "PRESTAMOes_ID" in table 'ACTIVOPRESTAMO'
ALTER TABLE "ACTIVOS"."ACTIVOPRESTAMO"
ADD CONSTRAINT "FK_ACTIVOPRESTAMO_PRESTAMO"
   FOREIGN KEY ("PRESTAMOes_ID")
   REFERENCES "ACTIVOS"."PRESTAMOS"
       ("ID")
 ;

-- Creating index for FOREIGN KEY 'FK_ACTIVOPRESTAMO_PRESTAMO'
CREATE INDEX "IX_FK_ACTIVOPRESTAMO_PRESTAMO"
ON "ACTIVOS"."ACTIVOPRESTAMO"
   ("PRESTAMOes_ID");

-- Creating foreign key on "CED_SOLICITA" in table 'PRESTAMOS'
ALTER TABLE "ACTIVOS"."PRESTAMOS"
ADD CONSTRAINT "FK_Solicita"
   FOREIGN KEY ("CED_SOLICITA")
   REFERENCES "ACTIVOS"."USUARIOS"
       ("IDUSUARIO")
;

-- Creating index for FOREIGN KEY 'FK_Solicita'
CREATE INDEX "IX_FK_Solicita"
ON "ACTIVOS"."PRESTAMOS"
   ("CED_SOLICITA");

-- Creating foreign key on "CED_APRUEBA" in table 'PRESTAMOS'
ALTER TABLE "ACTIVOS"."PRESTAMOS"
ADD CONSTRAINT "FK_Aprueba"
   FOREIGN KEY ("CED_APRUEBA")
   REFERENCES "ACTIVOS"."USUARIOS"
       ("IDUSUARIO")
 ;

-- Creating index for FOREIGN KEY 'FK_Aprueba'
CREATE INDEX "IX_FK_Aprueba"
ON "ACTIVOS"."PRESTAMOS"
   ("CED_APRUEBA");

-- Creating foreign key on "TIPO_ACTIVOID" in table 'ACTIVOS'
ALTER TABLE "ACTIVOS"."ACTIVOS"
ADD CONSTRAINT "FK_TIPO_ACTIVOACTIVO"
   FOREIGN KEY ("TIPO_ACTIVOID")
   REFERENCES "ACTIVOS"."TIPOS_ACTIVOS"
       ("ID")
;

-- Creating index for FOREIGN KEY 'FK_TIPO_ACTIVOACTIVO'
CREATE INDEX "IX_FK_TIPO_ACTIVOACTIVO"
ON "ACTIVOS"."ACTIVOS"
   ("TIPO_ACTIVOID");

-- Creating foreign key on "TIPOS_ACTIVOSID" in table 'EQUIPO_SOLICITADO'
ALTER TABLE "ACTIVOS"."EQUIPO_SOLICITADO"
ADD CONSTRAINT "FK_TIPOS_ACTIVOSEQUIPO_SOLICITADO"
   FOREIGN KEY ("TIPOS_ACTIVOSID")
   REFERENCES "ACTIVOS"."TIPOS_ACTIVOS"
       ("ID")
;

-- Creating index for FOREIGN KEY 'FK_TIPOS_ACTIVOSEQUIPO_SOLICITADO'
CREATE INDEX "IX_FK_TIPOS_ACTIVOSEQUIPO_SOLICITADO"
ON "ACTIVOS"."EQUIPO_SOLICITADO"
   ("TIPOS_ACTIVOSID");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
