//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos_PrestamosOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string RESPONSABLE { get; set; }
        public string ESTADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ACTIVOID { get; set; }
    
        public virtual ACTIVO ACTIVO { get; set; }
    }
}
