//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos_PrestamosOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string RESPONSABLE { get; set; }
        public string ESTADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ACTIVOID { get; set; }
        public Nullable<long> NUMERO_BOLETA { get; set; }
        public Nullable<System.DateTime> FECHA_RETIRO { get; set; }
        public Nullable<System.DateTime> FECHA_DEVOLUCION { get; set; }
        public string OBSERVACIONES_RECIBO { get; set; }
        public string NOMBRE_SOLICITANTE { get; set; }
    
        public virtual ACTIVO ACTIVO { get; set; }
    }
}
