//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos_PrestamosOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.PRESTAMOes = new HashSet<PRESTAMO>();
            this.PRESTAMOes1 = new HashSet<PRESTAMO>();
        }
    
        public string USUARIO1 { get; set; }
        public string CLAVE { get; set; }
        public string ANFITRION { get; set; }
        public string IDCONTACTO { get; set; }
        public string IDUSUARIO { get; set; }
        public string DESCRIPCION { get; set; }
        public string NOMBRE { get; set; }
        public string IDESTACION { get; set; }
        public decimal ESTADO { get; set; }
        public string CORREO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTAMO> PRESTAMOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTAMO> PRESTAMOes1 { get; set; }
    }
}
