//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos_PrestamosOET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public V_EMPLEADOS()
        {
            this.ACTIVOes = new HashSet<ACTIVO>();
        }
    
        public string APELLIDOS { get; set; }
        public string EMAIL { get; set; }
        public decimal ESTADO { get; set; }
        public Nullable<decimal> ESTADOCIVIL { get; set; }
        public string IDEMPLEADO { get; set; }
        public string IDENTIFICACION { get; set; }
        public string IDNACIONALIDAD { get; set; }
        public decimal IDTIPO { get; set; }
        public string NOMBRE { get; set; }
        public string NUMASEGURADO { get; set; }
        public decimal NUMEMPLEADO { get; set; }
        public string SEXO { get; set; }
        public Nullable<bool> ASOET { get; set; }
        public string CREA { get; set; }
        public string MODIFICA { get; set; }
        public Nullable<System.DateTime> CREADO { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string NUM_ASOET { get; set; }
        public Nullable<byte> PENSIONADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVO> ACTIVOes { get; set; }
    }
}
