//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activos_PrestamosOET.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class V_EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public V_EMPLEADOS()
        {
            this.ACTIVOes = new HashSet<ACTIVO>();
        }

        [Display(Name = "Apellidos")]
        public string APELLIDOS { get; set; }
        [Display(Name = "Correo electrónico")]
        public string EMAIL { get; set; }
        [Display(Name = "Estado en la compañía")]
        public decimal ESTADO { get; set; }
        public Nullable<decimal> ESTADOCIVIL { get; set; }
        public string IDEMPLEADO { get; set; }
        public string IDENTIFICACION { get; set; }
        public string IDNACIONALIDAD { get; set; }
        public decimal IDTIPO { get; set; }
        [Display(Name ="Nombre")]
        public string NOMBRE { get; set; }
        public string NUMASEGURADO { get; set; }
        public decimal NUMEMPLEADO { get; set; }
        public string SEXO { get; set; }
        public Nullable<bool> ASOET { get; set; }
        public string CREA { get; set; }
        public string MODIFICA { get; set; }
        public Nullable<System.DateTime> CREADO { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string NUM_ASOET { get; set; }
        public Nullable<byte> PENSIONADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVO> ACTIVOes { get; set; }
    }
}
